version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: comicspoiler_postgres
    environment:
      POSTGRES_USER: comicuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: comicspoilerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: comicspoiler_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build: ./comic_spoiler_login_backend
    container_name: comicspoiler_flask
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./comic_spoiler_login_backend/.env
    depends_on:
      - db
      
volumes:
  pgdata:
